### ISSUE TITLE
align edit permissions with those of article metadata

### ISSUE THREAD

**Issue by bozana** [ajnyga/funding#10]
s. https://github.com/ajnyga/funding/issues/7#issuecomment-328775810

the editing of the funding data should only be possible:
- for authors before the final submission
- for sub_editors and assistants if they are assigned to the submission
- for managers always

**Comment by bozana** [comment]
PR: https://github.com/ajnyga/funding/pull/11

**Comment by ajnyga** [comment]
Great thanks, so there was a way to control that :)

I think that the funding plugin is not only a great plugin itself, but also now a solid base to build any plugin that uses a grid to save data. Thanks again!

**Comment by ajnyga** [comment]
Just one more check that came to mind regarding this issue @bozana.

Does the funding data show to the reviewer at the moment? If it does, then there could be a possibility where the grant ID will reveal the name of the author.
