### ISSUE TITLE
How to handle new funder names in CrossRef exports

### ISSUE THREAD

**Issue by ajnyga** [ajnyga/funding#12]
In some cases a funder may be missing from the funder registry.

At the moment the plugin will let you to save a new name, but the ID for the funder will of course be missing. 

We need to find out what CrossRef thinks about this. Do they
1. Only want data with ID's, meaning that we should a) only allow funder names from the registry or b) only send funder data that has an ID to CrossRef
2. Allow funder names without ID's, and if so, how should this show in the XML

They do not give any clear answe to these questions here: https://www.crossref.org/services/content-registration/funding-data/

**Comment by ajnyga** [comment]
FYI @bozana 
" If the funder name cannot be matched in the Registry you may submit funder_name only and the funding body will be reviewed and considered for addition to the official Registry"
https://support.crossref.org/hc/en-us/articles/214360746-Funding-data-overview

**Comment by bozana** [comment]
@ajnyga, thanks a lot for all the information. Now I have some time again to take a look at the issues :-)
I would maybe ask Crossref Support about this issue.
On that page also this is written:
"Funder names should only be deposited without the accompanying ID when the funder is not found in the Registry. These deposits will not be considered valid records until such a time as the funder is added to the database and they are re-deposited with an ID. To this end it is critical that publishers do their utmost to match submitted or extracted funding data to the Registry, which covers all major international funders and a growing number of lesser-known organizations."
I.e., if a new name is deposited and then proved by Crossref it has to be re-deposited again, with the ID. 
Thus, to be on the safe side, maybe to only allow Funders that are in the registry and have an ID? In the case that there is a new Funder agency, the user could manually contact Crossref and then deposit the data?
I'll double check with Crossref support...
EDIT: The only concern I have to allow the storage and the deposit of such funders, that are not in the registry, is that it could be just a user typing mistake/typo...

**Comment by ajnyga** [comment]
Hi,

Yes, the smart thing to do is probably only allow values from the list. I think that the fundref widget had a link to a suggestion page of some sort, but that link is by default hidden in the github version. But it means that the widget also works the way you suggest so we should probably follow that model.

I know that tagit has a feature to only allow values from the list, but I am not sure whether it works with remote sources. Of course we can always give a warning when a DOI does not exist.

**Comment by bozana** [comment]
👍 I've send a question to Crossref support, so lets wait just a little bit more, for their answer.... In the meantime I can take a look in the code...

**Comment by ajnyga** [comment]
Great!
I am happy to do more coding as well, just wanted to wait with all these new comments before jumping into anything.

**Comment by bozana** [comment]
PR: https://github.com/ajnyga/funding/pull/19

**Comment by bozana** [comment]
@ajnyga, I haven't heard from Crossref support yet, but I think it would be best to allow only the funders from the registry. If OK, s. the PR.
