### ISSUE TITLE
Saving the whole URI vs saving just the prefix/suffix part

### ISSUE THREAD

**Issue by ajnyga** [ajnyga/funding#15]
Hi @bozana 

While thinking about the release, one more thing comes to mind. Should we save the whole URI as the identifier OR just the prefix/suffix part. I noticed that the CrossRef API is still returning the old dx.doi.org URI and maybe the protocoll could change later as well?

Of course these could be changed with a single line of sql later on...

**Comment by bozana** [comment]
Hmmm... I am not sure here... :-\\
It would be good to just save the DOI (prefix+suffix), but the JSON response is returning ID = suffix and URI = http://dx.doi.org... (s. e.g. http://api.crossref.org/funders?query=Schweizerischer+Nationalfonds+zur+F%C3%B6rderung+der+), thus we would need to extract it from the URI...
Also, when resolving such a funders DOI, s. http://data.crossref.org/fundingdata/funder/10.13039/501100001711, the response contains "id": "http://dx.doi.org/10.13039/501100001711"" :-O
So maybe to leave it for now as it is?

**Comment by ajnyga** [comment]
Yes, the thing with the old DOIs is that they will probably work for many years to come and it is very easy to convert those values later if needed.

So I will close this.
