### ISSUE TITLE
Add OpenAIRE support

### ISSUE THREAD

**Issue by ajnyga** [ajnyga/funding#17]
_This issue is based on the current OpenAIRE guidelines, but the guidelines are likely to change soon https://github.com/pkp/pkp-lib/issues/828#issuecomment-304266121_

After changing the database model according to this issue https://github.com/ajnyga/funding/issues/16 we can save funding data that will support also OpenAIRE and Datacite specifitions which have a bit more data.

### API for accessing OpenAIRE project data
http://api.openaire.eu/search/projects, example http://api.openaire.eu/search/projects?grantID=302009
http://api.openaire.eu/#sec_http-projects
https://wiki.surfnet.nl/display/standards/info-eu-repo#info-eu-repo-GrantAgreementIdentifiers

**Note!** Adding an OpenAIRE funding data could include a more controlled form, where for example the Funder and FundingProgramme would be selected with radio buttons.

We could still use the OpenAIRE funding data for CrossRef exports as well. Just have to make sure what data in the OpenAIRE model should be used.

For the latest and best version of the OpenAIRE plugin, see https://github.com/4Science/ojs/tree/ingv-fp7-post-grant/plugins/generic/openAIRE

**CrossRef**| |**Datacite**| |**OpenAIRE**
:-----:|:-----:|:-----:|:-----:|:-----:
funder_identifier|=|funderIdentifier|=|missing
funder_name|=|funderName|=|Funder*
award_number|=|awardNumber|=|projectID**
missing|=|awardTitle|=|ProjectName
missing|=|awardURI|=|missing
missing|=|missing|=|ProjectAcronym
missing|=|missing|=|FundingProgramme***

\* Only two options:   European Commission (EC) or Wellcome Trust (WT). For OAI the acronyms are   used.
** Not sure if the projectID is/can be   the exact same thing?
*** only two options: FP7 and H2020
 
Sources:
https://support.crossref.org/hc/en-us/articles/214360746-Funding-data-overview
https://guidelines.openaire.eu/en/latest/literature/field_projectid.html
https://schema.datacite.org/meta/kernel-4.0/

**Comment by bozana** [comment]
So I think we will have to wait a little bit for OpenAIRE support, right?

**Comment by ajnyga** [comment]
Yes, we will definitely have to wait for an update from OpenAIRE. But I am still a bit inclined to prepare for it with the schema update. Edit: unless there is an easy way to update the schema and data created with the plugin later on.

**Comment by ajnyga** [comment]
https://blogs.openaire.eu/?p=2397

**Comment by ajnyga** [comment]
@bozana the way I am planning to handle OpenAIRE support:
- new OpenAIRE plugin will use JATS XML via OAI to export data to OpenAIRE repo. This has been discussed with them and currently almost ready.
- the OAI plugin has a hook in the `toXml` method:  `HookRegistry::call('OAIMetadataFormat_OpenAIRE::findFunders', array(&$article));` 
- we can then use that hook in the Funding plugin to provide funding data for the OpenAIRE records. (the old FP7 programs etc. are obsolete: basically all funders can and should be listed).
- also other possible plugins that generate funding data can use the same hook 

what do you think?

**Comment by ajnyga** [comment]
Master branch now has initial support for OpenAIRE. The plugin injects funding data to OAI if https://github.com/ajnyga/oaiOpenAIRE plugin is enabled.

**Comment by bozana** [comment]
@ajnyga, yes that sounds and looks good :+1:
