### ISSUE TITLE
Can't add funder name to submission record

### ISSUE THREAD

**Issue by amandastevens** [ajnyga/funding#26]
A PKP hosting client using OJS 3.1 is having difficulty adding a new funder to the submission metadata. When you try to enter the funder name in the Funder Name and Identification field, no names come up, you can only enter the funder DOI. An endlessly scrolling search wheel appears. And then if you enter the funder DOI, the DOI displays in the submission metadata instead of the name of the funder.

**Comment by ajnyga** [comment]
Have not heard of an error like this before.

Is there something in the php error log or the javascript console?

**Comment by ajnyga** [comment]
Just checked this with 3.1.0.1 and the latest release of the plugin and it is working for me.

**Comment by bozana** [comment]
I also checked it with my local master branch and it is working for me too...

**Comment by ajnyga** [comment]
btw @bozana do I remember correctly that the plugin already supported cases where there are suborganisations available for a given name? Or did I just not come up with a name that has those when I tested a while ago?

**Comment by bozana** [comment]
I would say the second point is the case -- I think there are not many that has sub-organizations -- and I also forgot what I used to test it... :-P

**Comment by bozana** [comment]
Hmmm... I found one, I think: the funding organization "Schweizerischer Nationalfonds zur Förderung der Wissenschaftlichen Forschung" and its sub-organization "National Center of Competence in Research Quantum Science and Technology" (s. http://search.crossref.org/funders?descendants=true&q=Schweizerischer%20Nationalfonds%20zur%20F%C3%B6rderung%20der%20Wissenschaftlichen%20Forschung)

But it is currently not working for me... and my computer sounds like it is going to explode :-)

**Comment by ajnyga** [comment]
hmm the suborganization listing is not working... I am sure it was working at some point. Wonder if they changed something at the crossref end. I will take a closer look during the weekend.

But this is clearly not the issue the editor was reporting.

**Comment by bozana** [comment]
Ah, I fount it out -- it has to be https now... :-P
Will make a PR...

**Comment by ajnyga** [comment]
Nice, could be that this is causing the original issue as well if the server has https

**Comment by bozana** [comment]
hmmm... i am not sure if that was the problem -- the user should at least be able to use/search for the one funding organization... therefore no https is necessary and it worked for me... :-O

**Comment by ajnyga** [comment]
Ok, I was thinking if the browser was blocking http calls from a https Page...

Lähetetty Huawei-matkapuhelimestani

**Comment by bozana** [comment]
Aaaaa... maybe...

Now I also know Finish :-D

**Comment by ajnyga** [comment]
thanks @bozana! I would do a new release, but you know better how to deal with the plugin gallery integration. Is there something that needs to be done to make sure that the new version finds it's way to plugin gallery? Of course this needs a new minor version number?

btw. "Huawei" is an old Finnish word an means "hello" ;)

**Comment by bozana** [comment]
Hmmm... Yes, we could have then 2.1.1.1 version, but I am not sure how to then best call the release package funding-ojs-3_1_0-1.tar.gz or maybe funding-ojs-3_1_1-0.tar.gz... Hmmm... I've forgotten how was that... :-( I'll ask...

**Comment by ajnyga** [comment]
It would be great to get a small documentation on this. I mean how does the plugin maintainer add a new version of the plugin to the gallery?

Tagging @asmecher here as well...

**Comment by asmecher** [comment]
@ajnyga, I've started a little bit of work with another frequent contributor on documenting plugin gallery inclusions (and have some tools to share too) -- I'll see if I can dust it off for publishing on the PKP blog.

**Comment by ajnyga** [comment]
Sounds good! I think that with bugs like this (problem due to a change outside OJS), it would be important that the plugin maintainer could react fast and be able to offer a fix through the gallery.

**Comment by bozana** [comment]
@ajnyga, I think now we can have the next minor version 2.1.1.1 and pack the plugin in funding-ojs-3_1_1-0.tar.gz (@asmecher agreed/suggested :-))

**Comment by mfelczak** [comment]
@asmecher, any chance we might be able to update the release in the plugin gallery as well?

**Comment by asmecher** [comment]
This would need @bozana or @ajnyga to upload a new release in the Releases area, then I can update the plugin gallery XML!

**Comment by ajnyga** [comment]
@asmecher https://github.com/ajnyga/funding/releases/tag/2.1.1.1

@bozana I hope I did not break anything 😂

**Comment by ajnyga** [comment]
@bozana I did version 2.1.1.2 release for 3.1.1. No actual changes but for claritys sake I decided to change the version.xml. Can you check that and see if it is ok...

**Comment by ajnyga** [comment]
@asmecher I released a new version for 3.1.1 that can be added to the plugin gallery. There was a comment on the forum saying that the plugin does not work with 3.1.1 but I could not find anything wrong with it.

**Comment by bozana** [comment]
> @bozana I did version 2.1.1.2 release for 3.1.1. No actual changes but for claritys sake I decided to change the version.xml. Can you check that and see if it is ok...

You mean you change it for the master branch i.e. next coming release? Because you have changed it recently to 2.1.1.1, no? I think it is not important, just checking...

**Comment by ajnyga** [comment]
The 2.1.1.1 was the version that included the https fix you made some time ago. That was for 3.1.0.
The 2.1.1.2 release is for 3.1.1. It does not have other changes, sure, but seemed like a good idea to give it a different version number for claritys sake.
