### ISSUE TITLE
PHP Fatal error - OJS 3.4.0-5 - plugin installed from plugin gallery

### ISSUE THREAD

**Issue by rshost** [ajnyga/funding#47]
- OJS 3.4.0-5 
-  Funding plugin installed from plugin gallery

```
[22-May-2024 00:24:22 Europe/Berlin] PHP Fatal error:  Uncaught Exception: Unrecognized DAO UserGroupDAO! in /html/ojs/lib/pkp/classes/db/DAORegistry.php:77
Stack trace:
#0 /html/ojs/plugins/generic/funding/controllers/grid/FunderGridHandler.inc.php(305): PKP\db\DAORegistry::getDAO('...')
#1 /html/ojs/plugins/generic/funding/controllers/grid/FunderGridHandler.inc.php(129): FunderGridHandler->canAdminister(Object(PKP\user\User))
#2 /html/ojs/lib/pkp/classes/core/PKPRouter.php(331): FunderGridHandler->initialize(Object(APP\core\Request), Array)
#3 /html/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#4 /html/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#5 /html/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 /html/ojs/index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in /html/ojs/lib/pkp/classes/db/DAORegistry.php on line 77
```

**Comment by ajnyga** [comment]
What is the version of the plugin that was installed?

**Comment by ajnyga** [comment]
ah ok, I see it, it is an issue that happens probably just for subeditors.

I will do a fix and a new release to the gallery, thank you.

**Comment by rshost** [comment]
> What is the version of the plugin that was installed?

<release>3.4.0.2</release>
<date>2023-03-26</date>

Plugin gallery says: "Up to date"

**Comment by ajnyga** [comment]
yes I found that from the current version, it has gone by probably because it seems to only affect subeditor users

**Comment by mpbraendle** [comment]
Hi @ajnyga 

This error bites us as well: It is on line 305:

                $userGroupDao = DAORegistry::getDAO('UserGroupDAO');

This DAO doesn't exist anymore in OJS 3.4.0-5 - you should update your code accordingly.

OJS version: 3.4.0-5
Plugin version: 3.4.0.2

Here our error message:
Got error 'PHP message: PHP Fatal error:  Uncaught Exception: Unrecognized DAO UserGroupDAO! in /var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/classes/db/DAORegistry.php:77\nStack trace:\n#0 /var/www/virtual/ojs.chimia.ch/htdocs/ojs/plugins/generic/funding/controllers/grid/FunderGridHandler.inc.php(305): PKP\\db\\DAORegistry::getDAO()\n#1 /var/www/virtual/ojs.chimia.ch/htdocs/ojs/plugins/generic/funding/controllers/grid/FunderGridHandler.inc.php(129): FunderGridHandler->canAdminister()\n#2 /var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/classes/core/PKPRouter.php(331): FunderGridHandler->initialize()\n#3 /var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#4 /var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPComponentRouter->route()\n#5 /var/www/virtual/ojs.chimia.ch/htdocs/ojs/lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#6 /var/www/virtu...', referer: https://www.chimia.ch/chimia/authorDashboard/submission/7351

Error is produced in the submission workflow - just a spinning wheel is displayed for the funding part in the metadata.

**Comment by mpbraendle** [comment]
Instead you should use Repo::userGroup() - have a look at the CitationStyleLanguage plugin how it is done.

**Comment by mpbraendle** [comment]
I entered the submission as an author, probably this check on line 296 doesn't work anymore:

// Incomplete submissions can be edited. (Presumably author.)
                if ($submission->getDateSubmitted() == null) return true;
                
So the code continues and then stumbles over line 305 ...

**Comment by mpbraendle** [comment]
I have implemented a fix - you will get a PR soon.

**Comment by mpbraendle** [comment]
See https://github.com/ajnyga/funding/pull/49

**Comment by ajnyga** [comment]
thanks for this and sorry for the long delay!
