### ISSUE TITLE
PHP Fatal error - OJS 3.4.0-6 (Plugin v3.4.0.2) Uncaught Exception: Unrecognized DAO UserGroupDAO! 

### ISSUE THREAD

**Issue by nbimbe** [ajnyga/funding#50]
PHP Fatal error:  Uncaught Exception: Unrecognized DAO UserGroupDAO! in lib/pkp/classes/db/DAORegistry.php:77\nStack trace:\n#0 plugins/generic/funding/controllers/grid/FunderGridHandler.inc.php(305): PKP\\db\\DAORegistry::getDAO()\n#1 plugins/generic/funding/controllers/grid/FunderGridHandler.inc.php(129): FunderGridHandler->canAdminister()\n#2 lib/pkp/classes/core/PKPRouter.php(331): FunderGridHandler->initialize()\n#3 lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest()\n#4 lib/pkp/classes/core/Dispatcher.php(165): PKP\\core\\PKPComponentRouter->route()\n#5 lib/pkp/classes/core/PKPApplication.php(388): PKP\\core\\Dispatcher->dispatch()\n#6 index.php(21): PKP\\core\\PKPApplication->execute()\n#7 {main}\n  thrown in lib/pkp/classes/db/DAORegistry.php on line 77, referer: https://xxx.xxx/authorDashboard/submission/99999

**Comment by ajnyga** [comment]
This should be resolved and new version is released soon in the gallery. The changes are already here in the main branch.
