### ISSUE TITLE
Only funders from the Crossref registry are allowed

### ISSUE THREAD

**Issue by sbirAECA** [ajnyga/funding#56]
Good afternoon,
I have a clean version of OJS 3.4.0.5 installed and I added the funding plugin v3.4.0.3. And when I try to add a funder I always get the error ‘Only funders from the Crossref registry are allowed’ and it does not allow to save the selected institution, even though it is an institution recognised by the crossref registry.
Thank, you
![image](https://github.com/user-attachments/assets/ac6de2c5-8932-4ea6-9321-de61a57d0283)

**Comment by ajnyga** [comment]
hi, this was reported also on the PKP forum and a fix is coming today. The Crossref API had some changes.

**Comment by ajnyga** [comment]
New releases for 3.3 and 3.4 should fix this
https://github.com/ajnyga/funding/releases
